        <!--[if lte IE 9]>
            <div align="center">
                <h3>If you are seeing this, your browser is<br />not able to display the spidergraph!</h3>
                <p>
                	Please come back in:<br /> 
                	<a href='http://getfirefox.com'>FireFox</a><br />
                    <a href='http://www.opera.com/download/'>Opera</a><br />
                    <a href='http://www.apple.com/safari/'>Safari</a><br />
                    or<br />
                    <a href='http://www.microsoft.com/windows/downloads/ie/getitnow.mspx'>Internet Explorer 9</a>
                </p> 
                <p>
                	If you would rather not install another browser, please close Internet Explorer and return to this page.
                    When given the option to install ChromeFrame, please allow your computer to do so.  This will give
                    Internet Explorer the ability to display the spidergraphs.
                </p>
            </div>
        <![endif]-->
